spring:
  application:
    name: springsecurity
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: jdbc:postgresql://localhost:5432/security
    user: postgres
    password: postgres
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8090

app:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
